DROP TABLE IF EXISTS holidays;
DROP TABLE IF EXISTS entries;
DROP TABLE IF EXISTS transfers;
DROP TABLE IF EXISTS punches;
DROP TABLE IF EXISTS statuses;
DROP TABLE IF EXISTS employees;
DROP TABLE IF EXISTS identities;