// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: identity.sql

package db

import (
	"context"
)

const getEmployeeFromIdentities = `-- name: GetEmployeeFromIdentities :one
SELECT id, name FROM identities
WHERE name = 'employee' LIMIT 1
`

func (q *Queries) GetEmployeeFromIdentities(ctx context.Context) (Identity, error) {
	row := q.db.QueryRowContext(ctx, getEmployeeFromIdentities)
	var i Identity
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getHrAdminFromIdentities = `-- name: GetHrAdminFromIdentities :one
SELECT id, name FROM identities
WHERE name = 'HR-Admin' LIMIT 1
`

func (q *Queries) GetHrAdminFromIdentities(ctx context.Context) (Identity, error) {
	row := q.db.QueryRowContext(ctx, getHrAdminFromIdentities)
	var i Identity
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
