// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"time"
)

type Employee struct {
	ID         int32     `json:"id"`
	IdentityID int32     `json:"identity_id"`
	Code       string    `json:"code"`
	FullName   string    `json:"full_name"`
	Password   string    `json:"password"`
	Stock      int64     `json:"stock"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type Entry struct {
	ID         int64 `json:"id"`
	EmployeeID int32 `json:"employee_id"`
	// can be negative or positive
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type Holiday struct {
	ID   int32     `json:"id"`
	Date time.Time `json:"date"`
}

type Identity struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Punch struct {
	ID           int64     `json:"id"`
	EmployeeID   int32     `json:"employee_id"`
	WorkingDay   time.Time `json:"working_day"`
	WorkingHours int16     `json:"working_hours"`
	StatusID     int16     `json:"status_id"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Status struct {
	ID   int16  `json:"id"`
	Name string `json:"name"`
}

type Transfer struct {
	ID             int64 `json:"id"`
	FromEmployeeID int32 `json:"from_employee_id"`
	ToEmployeeID   int32 `json:"to_employee_id"`
	// must be positive
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}
