// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
)

type Querier interface {
	AddEmployeeStock(ctx context.Context, arg AddEmployeeStockParams) (Employee, error)
	CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	DeleteEmployeeById(ctx context.Context, id int32) error
	GetEmployee(ctx context.Context, id int32) (Employee, error)
	GetEmployeeForUpdate(ctx context.Context, id int32) (Employee, error)
	GetEmployeeFromIdentities(ctx context.Context) (Identity, error)
	GetEntry(ctx context.Context, id int64) (Entry, error)
	GetHrAdminFromIdentities(ctx context.Context) (Identity, error)
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	ListEmployees(ctx context.Context, arg ListEmployeesParams) ([]Employee, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error)
	ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfer, error)
	UpdateEmployeeWithStock(ctx context.Context, arg UpdateEmployeeWithStockParams) (Employee, error)
}

var _ Querier = (*Queries)(nil)
