// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: status.sql

package db

import (
	"context"
)

const getStatusByName = `-- name: GetStatusByName :one
SELECT id, name FROM statuses
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetStatusByName(ctx context.Context, name string) (Status, error) {
	row := q.db.QueryRowContext(ctx, getStatusByName, name)
	var i Status
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
